eureka:
  client:
    service-url:
      defaultZone: https://iahrari:pass@eureka-iahrari.herokuapp.com/eureka
  instance:
    statusPageUrl: https://${eureka.hostname}${management.endpoints.web.base-path}/info
    healthCheckUrl: https://${eureka.hostname}${management.endpoints.web.base-path}/health
    homePageUrl: https://${eureka.hostname}/
    
spring:
  cloud:
    discovery:
      enabled: true 
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
    
management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /management
